In [1]:
import torch
from torch.autograd import Variable

In [2]:
x = torch.ones(3)
x = Variable(x, requires_grad=True)
y = x**2
z = y*3

In [3]:
print(z)
grad = torch.Tensor([0.1, 1, 10])
z.backward(grad)

tensor([3., 3., 3.], grad_fn=<MulBackward0>)


In [4]:
print('----x.data----')
print(x.data)
print('----x.grad----')
print(x.grad)
print('----x.grad_fn----')
print(x.grad_fn)

----x.data----
tensor([1., 1., 1.])
----x.grad----
tensor([ 0.6000,  6.0000, 60.0000])
----x.grad_fn----
None
