In [1]:
import torch
from torch.autograd import Variable

In [2]:
x = torch.ones(2,2)
x = Variable(x, requires_grad=True)

In [3]:
print(x)
print(x.data)
print(x.grad)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]])
None
None


In [4]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
z = y**2
print(z)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [6]:
out=z.sum()
print(out)

tensor(36., grad_fn=<SumBackward0>)


In [7]:
out.backward()

In [8]:
print(x.data)
print(x.grad)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
tensor([[6., 6.],
        [6., 6.]])
None


In [9]:
print(y.data)
print(y.grad)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]])
None


/home/r320hyeon/anaconda3/envs/pattern/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  


In [10]:
print(z.data)
print(z.grad)
print(z.grad_fn)

tensor([[9., 9.],
        [9., 9.]])
None


/home/r320hyeon/anaconda3/envs/pattern/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  


In [11]:
print(out.data)
print(out.grad)
print(out.grad_fn)

tensor(36.)
None


/home/r320hyeon/anaconda3/envs/pattern/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  
