In [1]:
import torch 
from torch.autograd import Variable 
import torch.nn.functional as F

In [2]:
input = torch.ones(1,1,3,3)
filter = torch.ones(1,1,3,3)
input = Variable(input, requires_grad=True)
print(input)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)


In [3]:
filter = Variable(filter, requires_grad=True)
out = F.conv2d(input, filter)
print(out)

tensor([[[[9.]]]], grad_fn=<ThnnConv2DBackward>)


In [4]:
out.backward()
print(out.grad_fn)
print(input.grad)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
